### ISSUE TITLE
MappingSet#deobfuscate is called twice for return types

### ISSUE THREAD

**Issue by jpenilla** [jamiemansfield/Lorenz#53]
The following method is only used when remapping the return type of method signatures. It looks to me like the intention of the method was to remap if the given `Type` is a `FieldType`, and simply return the given type if it's not a `FieldType` (i.e. Void). But for some reason it calls `deobfuscate` a second time on the result of the first `deobfuscate` call. Again, this method is only used for return types, for parameter types the `FieldType`-accepting `deobfuscate` method is called directly.

https://github.com/CadixDev/Lorenz/blob/6851a5e4ad186ddc7a4cb5845c326a1e6665bfa7/lorenz/src/main/java/org/cadixdev/lorenz/MappingSet.java#L311-L316

With certain mapping sets, this causes `deobfuscate` to give invalid results. This was observed when trying to call `reverse` on a `MappingSet` containing class mappings like the following:

```
BinaryHeap -> Path
Path -> PathEntity
```

any mappings which had `PathEntity` as the return type were changed to have `BinaryHeap` as the return type in the reversed mappings.

Using my own reverse and deobfuscate methods which call `deobfuscate(FieldType)` only once fixed the issue for me, but given I'm not sure why it's remapping twice, I'm hesitant to call it the "proper" fix, so I haven't opened a PR.

**Comment by jamierocks** [comment]
Yeah, this looks like a derp on my behalf (I assume I wrote that code anyway).
